Spec: fix string.join example
bazelbuild/starlark pull request #141
Opened 2020-11-25 05:42 UTC by stepancheg

string is not iterable, thus it cannot be used as an argument to
`string.join`.

2020-11-26 14:55 UTC, alandonovan requested changes

2020-11-26 14:55 UTC, alandonovan commented on spec.md
> -"a".join("ctmrn")                       # "catamaran"
Let's change this to:

```
"a".join("ctmrn".elems())                 # "catamaran"
```

2020-11-26 16:52 UTC, stepancheg commented
Changed.

2020-11-26 17:35 UTC, alandonovan approved these changes

2020-11-30 23:18 UTC, alandonovan approved these changes

2020-11-30 23:18 UTC, merged